name: Pull Request Handler

on:
  repository_dispatch:
    type:
      - test-command

jobs:
  tf_init:
    name: Run tf-init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.14.8
          terraform_wrapper: true

      - name: Terraform Init
        working-directory: ./tests/public-install
        run: terraform init -input=false -no-color
